// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    debugmodule: require("./debugmodule"),
    definitionfilemodule: require("./definitionfilemodule"),
    mainprocessmodule: require("./mainprocessmodule"),
    networkinterfacemodule: require("./networkinterfacemodule"),
    pathmodule: require("./pathmodule"),
    scifilesmodule: require("./scifilesmodule"),
    startupmodule: require("./startupmodule"),
    testingfilesmodule: require("./testingfilesmodule")
  };

  module.exports = Modules;

}).call(this);
