// Generated by CoffeeScript 2.5.1
(function() {
  var cliargumentsmodule, extractMeowed, getHelpText, getOptions, log, meow, throwErrorOnUsageFail;

  cliargumentsmodule = {
    name: "cliargumentsmodule"
  };

  //region logPrintFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["cliargumentsmodule"] != null) {
      console.log("[cliargumentsmodule]: " + arg);
    }
  };

  //endregion

  //#############################################################
  //region node_modules
  meow = require("meow");

  //endregion

  //#############################################################
  cliargumentsmodule.initialize = function() {
    log("cliargumentsmodule.initialize");
  };

  //#############################################################
  //region internal functions
  getHelpText = function() {
    log("getHelpText");
    return `Usage
    $ interface-gen <arg1> <arg2>
    
Options
    required:
        arg1, --source <path/to/source>, -s <path/to/source>
            source of the interface definition in md

    optional:
        arg2, --name <interface-name>, -n <interface-name>
            specific interface name to be used for the generated files
            defaults to filename of the source.

Examples
    $  interface-gen definition.md sampleinterface
    ...`;
  };

  getOptions = function() {
    log("getOptions");
    return {
      flags: {
        source: {
          type: "string", // or string
          alias: "s"
        },
        name: {
          type: "string",
          alias: "n"
        }
      }
    };
  };

  extractMeowed = function(meowed) {
    var name, source;
    log("extractMeowed");
    source = "";
    name = "";
    if (meowed.input[0]) {
      source = meowed.input[0];
    }
    if (meowed.input[1]) {
      name = meowed.input[1];
    }
    if (meowed.flags.source) {
      source = meowed.flags.source;
    }
    if (meowed.flags.name) {
      name = meowed.flags.name;
    }
    return {source, name};
  };

  throwErrorOnUsageFail = function(extract) {
    log("throwErrorOnUsageFail");
    if (!extract.source) {
      throw new Error("Usag error: no source has been defined!");
    }
    if (!(typeof extract.source === "string")) {
      throw new Error("Usage error: defined source is not a string!");
    }
  };

  //endregion

  //#############################################################
  //region exposed functions
  cliargumentsmodule.extractArguments = function() {
    var extract, meowed;
    log("cliargumentsmodule.extractArguments");
    meowed = meow(getHelpText(), getOptions());
    extract = extractMeowed(meowed);
    throwErrorOnUsageFail(extract);
    return extract;
  };

  //endregion exposed functions
  module.exports = cliargumentsmodule;

}).call(this);
