// Generated by CoffeeScript 2.6.1
import {
  addModulesToDebug
} from "thingy-debug";

//###############################################################################
addModulesToDebug({
  // cliargumentsmodule: true
  // configmodule: true
  // definitionfilemodule: true
  mainprocessmodule: true,
  // networkinterfacemodule: true
  pathhandlermodule: true
});

// scifilesmodule: true
// startupmodule: true
// testingfilesmodule: true
