// Generated by CoffeeScript 2.6.1
//#############################################################################
export var modulesToDebug = {
  unbreaker: true,
  // cliargumentsmodule: true
  // configmodule: true
  // mainprocessmodule: true
  // networkinterfacemodule: true
  // scifilesmodule: true
  // startupmodule: true
  testingfilesmodule: true
};
