// Generated by CoffeeScript 2.5.1
(function() {
  var HJSON, absolutePath, definitionEndKey, definitionStartKey, definitionfilemodule, dirname, extractFromSlice, extractInterface, file, filename, fs, getPathData, interfaceObject, log, olog, ostr, path, print, requestKey, responseKey, routeDetect, routeKey, sliceFile, slices;

  definitionfilemodule = {
    name: "definitionfilemodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["definitionfilemodule"] != null) {
      console.log("[definitionfilemodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  //region modulesFromEnvironment
  path = require("path");

  fs = require("fs");

  HJSON = require("hjson");

  //###########################################################
  absolutePath = "";

  dirname = "";

  filename = "";

  file = "";

  slices = [];

  //###########################################################
  interfaceObject = {};

  //###########################################################
  routeDetect = /^[a-z0-9]+/i;

  routeKey = "### /";

  requestKey = "#### request";

  responseKey = "#### response";

  definitionStartKey = "```json";

  definitionEndKey = "```";

  //endregion

  //###########################################################
  definitionfilemodule.initialize = function() {
    log("definitionfilemodule.initialize");
  };

  
  //###########################################################
  //region internalFunctions
  getPathData = function(source) {
    absolutePath = path.resolve(source);
    dirname = path.dirname(absolutePath);
    filename = path.basename(absolutePath);
    log("- - -");
    log(absolutePath);
    log(dirname);
    log(filename);
    log("= = =");
  };

  //###########################################################
  sliceFile = function() {
    var index, nextIndex;
    index = file.indexOf(routeKey);
    while (index >= 0) {
      index += routeKey.length;
      nextIndex = file.indexOf(routeKey, index);
      if (nextIndex < 0) {
        slices.push(file.slice(index));
      } else {
        slices.push(file.slice(index, nextIndex));
      }
      index = nextIndex;
    }
  };

  //###########################################################
  extractInterface = function() {
    var i, len, slice;
    for (i = 0, len = slices.length; i < len; i++) {
      slice = slices[i];
      extractFromSlice(slice);
    }
  };

  extractFromSlice = function(slice) {
    var requestDefinition, requestDefinitionEnd, requestDefinitionStart, requestDefinitionString, requestIndex, responseDefinitionEnd, responseDefinitionStart, responseDefinitionString, responseIndex, route;
    route = routeDetect.exec(slice);
    requestIndex = slice.indexOf(requestKey);
    if (requestIndex < 0) {
      throw new Error("File Corrupt! Expected '#### request' in route slice!");
    }
    requestIndex += requestKey.length;
    requestDefinitionStart = slice.indexOf(definitionStartKey, requestIndex);
    if (requestDefinitionStart < 0) {
      throw new Error("File Corrupt! Expected '```json' to start request definition!");
    }
    requestDefinitionStart += definitionStartKey.length;
    requestDefinitionEnd = slice.indexOf(definitionEndKey, requestDefinitionStart);
    if (requestDefinitionEnd < 0) {
      throw new Error("File Corrupt! Expected '```' to end request definition!");
    }
    responseIndex = slice.indexOf(responseKey, requestDefinitionEnd);
    if (responseIndex < 0) {
      throw new Error("File Corrupt! Expected '#### response' definition in route slice!");
    }
    responseIndex += responseKey.length;
    responseDefinitionStart = slice.indexOf(definitionStartKey, responseIndex);
    if (responseDefinitionStart < 0) {
      throw new Error("File Corrupt! Expected '```json' to start response definition!");
    }
    responseDefinitionStart += definitionStartKey.length;
    responseDefinitionEnd = slice.indexOf(definitionEndKey, responseDefinitionStart);
    if (responseDefinitionEnd < 0) {
      throw new Error("File Corrupt! Expected '```' to end response definition!");
    }
    requestDefinitionString = slice.slice(requestDefinitionStart, requestDefinitionEnd);
    requestDefinition = HJSON.parse(requestDefinitionString);
    responseDefinitionString = slice.slice(responseDefinitionStart, responseDefinitionEnd);
    interfaceObject[route] = Object.keys(requestDefinition);
  };

  //endregion

  //###########################################################
  //region exposedFunctions
  definitionfilemodule.digestFile = function(source) {
    getPathData(source);
    file = fs.readFileSync(absolutePath, 'utf8');
    sliceFile();
    extractInterface();
  };

  definitionfilemodule.interfaceObject = interfaceObject;

  //endregion 
  module.exports = definitionfilemodule;

}).call(this);
