// Generated by CoffeeScript 2.6.1
//###########################################################
//region debug
var log, olog;

import {
  createLogFunctions,
  debugOn
} from "thingy-debug";

({log, olog} = createLogFunctions("filesparsermodule"));

import {
  //endregion

  //###########################################################
  DocumentationFileParser
} from "./documentationparser.js";

import {
  InterfaceFileParser
} from "./interfaceparser.js";

//###########################################################
export var initialize = function() {
  log("initialize");
  // debugOn("documentationparser")
  debugOn("interfaceparser");
};

//###########################################################
export var parseAllFiles = function() {
  var documentationParser, interfaceParser;
  log("parseAllFiles");
  documentationParser = new DocumentationFileParser();
  if (documentationParser.fileExists) {
    documentationParser.parse();
  } else {
    log("No documentation file found!");
  }
  interfaceParser = new InterfaceFileParser();
  if (interfaceParser.fileExists) {
    interfaceParser.parse();
  } else {
    log("No interface file found!");
  }
};
