// Generated by CoffeeScript 2.6.1
//###########################################################
//region debug
var log, olog;

import {
  createLogFunctions,
  debugOn
} from "thingy-debug";

({log, olog} = createLogFunctions("filesparsermodule"));

import {
  //endregion

  //###########################################################
  DocumentationFileParser
} from "./documentationparser.js";

//###########################################################
export var initialize = function() {
  log("initialize");
  debugOn("documentationparser");
};

//###########################################################
//Implement or Remove :-)
export var parseAllFiles = function() {
  var documentationParser;
  log("parseAllFiles");
  documentationParser = new DocumentationFileParser();
  if (documentationParser.fileExists) {
    documentationParser.parse();
  } else {
    log("No documentation file found!");
  }
};
