// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

import * as p from "./pathmodule.js";

import * as df from "./definitionfilemodule.js";

import * as ni from "./networkinterfacemodule.js";

import * as sf from "./scifilesmodule.js";

import * as tf from "./testingfilesmodule.js";

//endregion

//###########################################################
export var execute = function(e) {
  var interfaceObject, name;
  log("execute");
  df.digestFile(e.source);
  interfaceObject = df.interfaceObject;
  if (e.name != null) {
    name = e.name;
  } else {
    name = p.basename;
  }
  ni.writeFile(interfaceObject, name);
  sf.writeFiles(interfaceObject, name);
  tf.writeFiles(interfaceObject, name);
};
