// Generated by CoffeeScript 2.6.1
//#############################################################################
//region logPrintFunctions
var cfg, definitionFile, log, networkInterface, olog, ostr, p, print, sciFiles, testingFiles;

log = function(arg) {
  if (allModules.debugmodule.modulesToDebug["mainprocessmodule"] != null) {
    console.log("[mainprocessmodule]: " + arg);
  }
};

olog = function(o) {
  return log("\n" + ostr(o));
};

ostr = function(o) {
  return JSON.stringify(o, null, 4);
};

print = function(arg) {
  return console.log(arg);
};

//endregion

//###########################################################
//region modulesFromEnvironment
p = null;

cfg = null;

definitionFile = null;

networkInterface = null;

sciFiles = null;

testingFiles = null;

//endregion

//###########################################################
export var initialize = function() {
  log("initialize");
  p = allModules.pathmodule;
  cfg = allModules.configmodule;
  definitionFile = allModules.definitionfilemodule;
  networkInterface = allModules.networkinterfacemodule;
  sciFiles = allModules.scifilesmodule;
  testingFiles = allModules.testingfilesmodule;
};


//###########################################################
export var execute = function(e) {
  var interfaceObject, name;
  log("execute");
  definitionFile.digestFile(e.source);
  interfaceObject = definitionFile.interfaceObject;
  if (e.name != null) {
    name = e.name;
  } else {
    name = p.basename;
  }
  networkInterface.writeFile(interfaceObject, name);
  sciFiles.writeFiles(interfaceObject, name);
  testingFiles.writeFiles(interfaceObject, name);
};
