// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var getInterfaceName, log, olog, template;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("networkinterfacemodule"));

import fs from "fs";

import M from "mustache";

import * as p from "./pathmodule.js";

//endregion

//###########################################################
//region templates
template = `import { postData } from "thingy-network-base"

############################################################
#region routes
{{#routes}}
export {{route}} = (sciURL, {{args}}) ->
    requestObject = { {{args}} }
    requestURL = sciURL+"/{{route}}"
    return postData(requestURL, requestObject)

{{/routes}}
#endregion`;

//endregion

//###########################################################
getInterfaceName = function(name) {
  name = name.toLowerCase();
  if (name.indexOf("interface") < 0) {
    name = name + "interface";
  }
  return name;
};

//###########################################################
export var writeFile = function(interfaceObject, name) {
  var filePath, interfaceFile;
  log("writeFile");
  name = getInterfaceName(name);
  interfaceObject.name = name;
  interfaceFile = M.render(template, interfaceObject);
  filePath = p.getFilePath(name + ".coffee");
  fs.writeFileSync(filePath, interfaceFile);
};
