// Generated by CoffeeScript 2.5.1
(function() {
  var log, networkinterfacemodule, olog, ostr, p, print;

  networkinterfacemodule = {
    name: "networkinterfacemodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["networkinterfacemodule"] != null) {
      console.log("[networkinterfacemodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  p = null;

  //###########################################################
  networkinterfacemodule.initialize = function() {
    log("networkinterfacemodule.initialize");
    p = allModules.pathmodule;
  };

  
  //###########################################################
  //region exposedFunctions
  networkinterfacemodule.writeFile = function(interfaceObject, name) {
    log("networkinterfacemodule.writeFile");
  };

  //endregion
  module.exports = networkinterfacemodule;

}).call(this);
