// Generated by CoffeeScript 2.6.1
//###########################################################
//region printLogFunctions
var log, obj, olog, ostr, print;

log = function(arg) {
  if (allModules.debugmodule.modulesToDebug["pathmodule"] != null) {
    console.log("[pathmodule]: " + arg);
  }
};

ostr = function(obj) {
  return JSON.stringify(obj, null, 4);
};

olog = function(obj) {
  return log("\n" + ostr(obj));
};

print = function(arg) {
  return console.log(arg);
};

import path from "path";

//###########################################################
obj = {};

obj.absolutePath = "";

obj.dirname = "";

obj.filename = "";

obj.basename = "";

//###########################################################
export var digestPath = function(source) {
  obj.absolutePath = path.resolve(source);
  obj.dirname = path.dirname(pathmodule.absolutePath);
  obj.filename = path.basename(pathmodule.absolutePath);
  obj.basename = pathmodule.filename.split(".")[0];
  log("- - -");
  log(obj.absolutePath);
  log(obj.dirname);
  log(obj.filename);
  log(obj.basename);
  log("= = =");
};

export var getFilePath = function(name) {
  return path.resolve(pathmodule.dirname, name);
};

export default obj;
