// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, obj, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("pathmodule"));

import path from "path";

//###########################################################
obj = {};

obj.absolutePath = "";

obj.dirname = "";

obj.filename = "";

obj.basename = "";

//###########################################################
export var digestPath = function(source) {
  log("digestPath");
  log(source);
  obj.absolutePath = path.resolve(source);
  obj.dirname = path.dirname(obj.absolutePath);
  obj.filename = path.basename(obj.absolutePath);
  obj.basename = obj.filename.split(".")[0];
  olog(obj);
};

export var getFilePath = function(name) {
  return path.resolve(obj.dirname, name);
};

//###########################################################
export default obj;
