// Generated by CoffeeScript 2.6.1
//###########################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("sectionobject"));

import * as M from "mustache";

//###########################################################
export var SectionObject = class SectionObject {
  constructor(name1) {
    this.name = name1;
    this.titleLine = null;
    this.descriptionLines = [];
    this.routeNames = [];
  }

  addRoute(name) {
    return this.routeNames.push(name);
  }

};
