// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog, printError, printSuccess;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("startupmodule"));

import chalk from 'chalk';

import * as mp from "./mainprocessmodule.js";

import * as ca from "./cliargumentsmodule.js";

//endregion

//#############################################################################
printSuccess = function(arg) {
  return console.log(chalk.green(arg));
};

printError = function(arg) {
  return console.log(chalk.red(arg));
};

//#############################################################################
export var initialize = function() {
  var cfg, cliArguments, mainProcess;
  log("startupmodule.initialize");
  mainProcess = allModules.mainprocessmodule;
  cfg = allModules.configmodule;
  cliArguments = allModules.cliargumentsmodule;
};

//#############################################################################
export var cliStartup = async function() {
  var e, err;
  log("cliStartup");
  try {
    e = ca.extractArguments();
    await mp.execute(e);
    return printSuccess('All done!');
  } catch (error) {
    err = error;
    printError("Error!");
    printError(err);
    if (err.stack) {
      printError(err.stack);
    }
    return process.exit(-1);
  }
};
